name: Deploy staging hello world

on:
  workflow_dispatch:
    inputs:
      image:
        type: string
        description: name of the image
        require: true
      digest:
        required: true
        type: string
        description: digest sha256:xxx

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  gate:
    permissions:
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.
      contents: read
    uses: laurentsimon/slsa-policy/.github/workflows/verify-slsa.yml@v0.0.1
    with:
      image: ${{ inputs.image }}
      digest: ${{ inputs.digest }}
      registry-username: ${{ github.actor }}
      policy-path: .slsa/policy-staging.json
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  result:
    needs: [gate]
    runs-on: ubuntu-latest
    steps:
      - name: Run it
        env:
          OUTCOME: ${{ needs.gate.outputs.outcome }}
          IMAGE: ${{ inputs.image }}
          DIGEST: ${{ inputs.digest }}
        run: |
          echo "${IMAGE}@${DIGEST}:"
          echo "> ${OUTCOME}"
